language: python

# Build on both osx VM and Ubuntu container.
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
      env: TRAVIS_PYTHON_VERSION=3.6

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - which python; python --version


install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest

script:
  - pytest
